<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Festival.Model\Festival.Model.csproj" />
      <ProjectReference Include="..\Festival.Persistence\Festival.Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="festival.db">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Hubs\" />
    </ItemGroup>

</Project>
