<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Festival.Model\Festival.Model.csproj" />
      <ProjectReference Include="..\Festival.Networking\Festival.Networking.csproj" />
      <ProjectReference Include="..\Festival.Persistence\Festival.Persistence.csproj" />
      <ProjectReference Include="..\Festival.Services\Festival.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.2" />
      <PackageReference Include="System.Configuration.ConfigurationManager" Version="11.0.0-preview.3.26207.106" />
      <PackageReference Include="System.Data.SQLite" Version="2.0.3" />
    </ItemGroup>

    <ItemGroup>
      <None Update="festival.db">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
