<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>

    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>

    <UseWindowsForms>true</UseWindowsForms>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.2" />
    <PackageReference Include="System.Data.SQLite" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Festival.Controller\Festival.Controller.csproj" />
    <ProjectReference Include="..\Festival.Domain\Festival.Domain.csproj" />
    <ProjectReference Include="..\Festival.Repository\Festival.Repository.csproj" />
    <ProjectReference Include="..\Festival.Service\Festival.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LoginForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MainView.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
